### ISSUE TITLE
Issue in line 91

### ISSUE THREAD

**Issue by HumanChwan** [VivekRanjan94/Projects#3]
@VivekRanjan94 : 
In the case when user enters 'y' for repetitions, There might be a problem.   
`while(!(guess>minValue && guess<maxValue && checkRepeat(guess, numOfDigits) == repeat));`  
Now if you'll see that if repetition case is true(i.e. `userInpRepeat == 'y'`) then all the user inputs must have repetitions as well, but the to be guessed number might not be repeated.   
For eg : `userInpRepeat == 'y'`  and user enters `1234`, the while loop will go on again, because `checkRepeat(guess, numOfDigits)` will not be equal to  `repeat` . but 1234 can be  the answer

**Comment by VivekRanjan94** [comment]
Makes sense
